import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd(),dist=path.join(root,'dist');
fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.cpSync(path.join(root,'public'),dist,{recursive:true});
const records=fs.readdirSync(path.join(root,'data/outputs')).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(fs.readFileSync(path.join(root,'data/outputs',f),'utf8'))).sort((a,b)=>b.journal.year-a.journal.year);
const copy={ja:{home:'ホーム',outputs:'研究成果',about:'このリポジトリについて',policy:'リポジトリ方針',contact:'お問い合わせ',switch:'English',title:'ななーる訪問看護デベロップメントセンターリポジトリ',intro:'ななーる訪問看護デベロップメントセンターに関連する研究成果を公開しています。',view:'研究成果を見る',latest:'研究成果',all:'すべて見る',sample:'サンプル（実在する論文ではありません）',details:'詳細を見る',search:'タイトル・著者・キーワードで検索',publication:'出版情報',file:'リポジトリ掲載ファイル',abstract:'抄録',keywords:'キーワード',affiliations:'所属',posted:'リポジトリ公開日',license:'ライセンス',empty:'現在、公開中の研究成果はありません。'},en:{home:'Home',outputs:'Research Outputs',about:'About',policy:'Repository Policy',contact:'Contact',switch:'日本語',title:'Nana-r Home-visit Nursing Development Center Repository',intro:'Research outputs associated with the Nana-r Home-visit Nursing Development Center.',view:'View research outputs',latest:'Research outputs',all:'View all',sample:'Sample record — not a real publication',details:'View details',search:'Search title, author, or keyword',publication:'Publication',file:'Repository file',abstract:'Abstract',keywords:'Keywords',affiliations:'Affiliations',posted:'Repository publication date',license:'License',empty:'There are currently no published research outputs.'}};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const alt=l=>l==='ja'?'en':'ja';
const localized=(value,l)=>value&&typeof value==='object'&&!Array.isArray(value)?(value[l]??value.en??value.ja??''):value;
const localizedList=(value,l)=>Array.isArray(value)?value:(localized(value,l)||[]);
const authorNames=(record,l)=>record.authors.map(author=>localized(author.name,l)).join(', ');
function footer(l){return `<footer class="footer"><div class="wrap footer-grid"><div><strong>${l==='ja'?'ななーる訪問看護デベロップメントセンター':'Nana-r Home-visit Nursing Development Center'}</strong><div class="small">〒560-0085 豊中市上新田3丁目6-17-301</div></div><div><a href="https://www.nana-dc.jp/">${l==='ja'?'公式サイト':'Official website'}</a><div class="small">© ${new Date().getFullYear()} Nana-r Home-visit Nursing Development Center</div></div></div></footer>`}
function page(l,title,body,description=copy[l].intro,extra='',alternatePath=''){const t=copy[l];return `<!doctype html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(t.title)}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="icon" href="/assets/nana-r-logo.png"><link rel="stylesheet" href="/assets/site.css">${extra}</head><body><a class="skip" href="#main">Skip to content</a><header class="topbar"><div class="wrap header"><a href="/${l}/"><img class="logo" src="/assets/nana-r-logo.png" alt="ななーる訪問看護デベロップメントセンター"></a><nav class="nav" aria-label="Main navigation"><a href="/${l}/">${t.home}</a><a href="/${l}/outputs/">${t.outputs}</a><a href="/${l}/about/">${t.about}</a><a href="/${l}/policy/">${t.policy}</a><a href="/${l}/contact/">${t.contact}</a><a class="lang" href="/${alt(l)}/${alternatePath}">${t.switch}</a></nav></div></header><main id="main">${body}</main>${footer(l)}<script src="/assets/site.js"></script></body></html>`}
const card=(r,l)=>`<article class="card" data-output>${r.sample?`<span class="tag">${copy[l].sample}</span>`:''}<div class="meta">${esc(r.id)} · ${esc(r.journal.year)} · ${esc(localized(r.journal.name,l))}</div><h3>${esc(localized(r.title,l))}</h3><p>${esc(authorNames(r,l))}</p><span hidden>${localizedList(r.keywords,l).map(esc).join(' ')}</span><a href="/${l}/outputs/${r.id.toLowerCase()}/">${copy[l].details} →</a></article>`;
function home(l){const t=copy[l],items=records.length?`<div class="cards">${records.slice(0,3).map(r=>card(r,l)).join('')}</div>`:`<p>${t.empty}</p>`;return page(l,t.title,`<section class="hero"><div class="wrap"><div class="eyebrow">Repository</div><h1>${t.title}</h1><p class="lede">${t.intro}</p><div class="actions"><a class="button" href="/${l}/outputs/">${t.view}</a></div></div></section><section><div class="wrap"><div class="section-head"><h2>${t.latest}</h2><a href="/${l}/outputs/">${t.all} →</a></div>${items}</div></section>`)}
function listing(l){const t=copy[l],items=records.length?`<div class="cards">${records.map(r=>card(r,l)).join('')}</div>`:`<p>${t.empty}</p>`;return page(l,t.outputs,`<div class="page-head"><div class="wrap"><h1 class="page-title">${t.outputs}</h1><p>${l==='ja'?'新しい出版年順に掲載しています。':'Listed by publication year, newest first.'}</p></div></div><section><div class="wrap"><div class="tools"><input type="search" data-output-search placeholder="${t.search}" aria-label="${t.search}"><span>${records.length} ${l==='ja'?'件':'record(s)'}</span></div>${items}</div></section>`,undefined,'','outputs/')}
function detail(r,l){const t=copy[l],j=r.journal,recordTitle=localized(r.title,l),recordAbstract=localized(r.abstract,l),journalName=localized(j.name,l),names=authorNames(r,l),affiliations=r.affiliations.map(value=>localized(value,l)),keywords=localizedList(r.keywords,l),doi=j.doi?`<a href="https://doi.org/${esc(j.doi)}">${esc(j.doi)}</a>`:(l==='ja'?'未登録':'Not provided'),pdf=r.repository_file.url?`<a class="button" href="${esc(r.repository_file.url)}">${l==='ja'?'PDFを表示':'View PDF'}</a>`:(l==='ja'?'ファイル未登録':'No file provided'),license=r.repository_file.license?.name?(r.repository_file.license.url?`<a href="${esc(r.repository_file.license.url)}">${esc(r.repository_file.license.name)}</a>`:esc(r.repository_file.license.name)):(l==='ja'?'未設定':'Not specified'),abstractSection=recordAbstract?`<h2>${t.abstract}</h2><p>${esc(recordAbstract)}</p>`:'';const academic=`<meta name="citation_title" content="${esc(recordTitle)}">${r.authors.map(a=>`<meta name="citation_author" content="${esc(localized(a.name,l))}">`).join('')}<meta name="citation_publication_date" content="${esc(j.year)}"><meta name="citation_journal_title" content="${esc(journalName)}">${j.doi?`<meta name="citation_doi" content="${esc(j.doi)}">`:''}`;return page(l,recordTitle,`<div class="page-head"><div class="wrap">${r.sample?`<div class="notice">${t.sample}</div>`:''}<div class="eyebrow">${esc(r.id)}</div><h1 class="page-title">${esc(recordTitle)}</h1><p>${esc(names)}</p></div></div><section><div class="wrap prose"><h2>${t.publication}</h2><dl><dt>${t.affiliations}</dt><dd>${affiliations.map(esc).join('<br>')}</dd><dt>Journal</dt><dd>${esc(journalName)}</dd><dt>Year / Volume / Issue / Pages</dt><dd>${[j.year,j.volume,j.issue,j.pages].filter(Boolean).map(esc).join(' / ')}</dd><dt>DOI</dt><dd>${doi}</dd></dl><h2>${t.file}</h2><dl><dt>Manuscript type</dt><dd>${esc(r.repository_file.type)}</dd><dt>${t.posted}</dt><dd>${esc(r.repository_file.posted)}</dd><dt>${t.license}</dt><dd>${license}</dd><dt>PDF</dt><dd>${pdf}</dd></dl>${abstractSection}<h2>${t.keywords}</h2><p>${keywords.map(esc).join(' · ')}</p></div></section>`,recordAbstract||copy[l].intro,academic,`outputs/${r.id.toLowerCase()}/`)}
function info(l,type){const ja=l==='ja';const x={about:[copy[l].about,`<p>${ja?'ななーる訪問看護デベロップメントセンターに関連する研究成果を公開するリポジトリです。':'This repository publishes research outputs associated with the Nana-r Home-visit Nursing Development Center.'}</p><h2>${ja?'運営主体':'Operator'}</h2><p>${ja?'ななーる訪問看護デベロップメントセンター':'Nana-r Home-visit Nursing Development Center'}</p><p><a href="https://www.nana-dc.jp/">${ja?'公式サイトを見る':'Visit the official website'} →</a></p>`],policy:[copy[l].policy,`<p>${ja?'本リポジトリは、センターに関連する出版済み研究成果と、公開が許可された原稿を収載します。査読中の成果は対象外です。':'This repository contains published research associated with the Center and manuscript files permitted for public access. Works under review are excluded.'}</p><h2>${ja?'正本とDOI':'Version of record and DOI'}</h2><p>${ja?'ジャーナルの公式公開版が正本です。表示するDOIはジャーナル側のものであり、本リポジトリ独自のDOIは付与しません。':'The official journal publication is the version of record. Displayed DOIs belong to the journal; this repository does not mint separate DOIs.'}</p><h2>${ja?'著作権と利用条件':'Copyright and reuse'}</h2><p>${ja?'ファイルは出版社方針の範囲で公開し、再利用条件は各ファイルの権利状況に従います。':'Files are shared within publisher policies. Reuse is governed by the rights status of each file.'}</p>`],contact:[copy[l].contact,`<p><strong>${ja?'ななーる訪問看護デベロップメントセンター':'Nana-r Home-visit Nursing Development Center'}</strong></p><p>〒560-0085 豊中市上新田3丁目6-17-301</p><p><a class="button" href="https://www.nana-dc.jp/">${ja?'公式サイトから問い合わせる':'Contact via the official website'}</a></p>`]}[type];return page(l,x[0],`<div class="page-head"><div class="wrap"><h1 class="page-title">${x[0]}</h1></div></div><section><div class="wrap prose">${x[1]}</div></section>`,undefined,'',`${type}/`)}
function write(rel,html){const p=path.join(dist,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,html)}
write('index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=./ja/"><title>Nana-r Home-visit Nursing Development Center Repository</title>');
for(const l of ['ja','en']){write(`${l}/index.html`,home(l));write(`${l}/outputs/index.html`,listing(l));for(const type of ['about','policy','contact'])write(`${l}/${type}/index.html`,info(l,type));for(const r of records)write(`${l}/outputs/${r.id.toLowerCase()}/index.html`,detail(r,l))}
write('.nojekyll','');console.log(`Generated ${records.length} output record(s) in dist/`);
